# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


# Acessando Dimensões no Array

In [1]:
# Importando o Numpy
import numpy as np

In [2]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [3]:
my_array

array([[0.49080726, 0.92810448],
       [0.78635381, 0.37504796],
       [0.77113838, 0.17686449],
       [0.3463719 , 0.01252238],
       [0.68737942, 0.21354206],
       [0.63746391, 0.16731038],
       [0.67390387, 0.33367786],
       [0.90363338, 0.84001329],
       [0.85987897, 0.24926311],
       [0.59734426, 0.65838696]])

In [4]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.49080726, 0.92810448])

In [6]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.49080726479217607

In [7]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.92810447940332

In [8]:
# Segundo elemento da coluna 1
my_array[1][1]

0.3750479554660856

In [9]:
# Segundo elemento da coluna escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.3750479554660856

In [10]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.92810448, 0.37504796, 0.17686449])

In [11]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([9.28104479, 3.75047955, 1.76864493, 0.1252238 , 2.13542065,
       1.6731038 , 3.33677864, 8.40013288, 2.49263113, 6.58386962])

In [12]:
# Comparação retorna indices
my_array > 0.50

array([[False,  True],
       [ True, False],
       [ True, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True,  True],
       [ True, False],
       [ True,  True]])

In [13]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.92810448, 0.78635381, 0.77113838, 0.68737942, 0.63746391,
       0.67390387, 0.90363338, 0.84001329, 0.85987897, 0.59734426,
       0.65838696])

# Carregar Arrays NumPy a partir de arquivos de Texto

In [14]:
import numpy as np

In [15]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('C:/CursoDataScience/MaterialModulo4/Exercicios/dataset_array.txt', delimiter=',')

In [16]:
dataset.shape

(6,)

In [17]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [18]:
# carregando um arquivo dividido em 3 arrays
a, b, c = np.loadtxt('C:/CursoDataScience/MaterialModulo4/materiais-de-apoio-numpy/dataset_valores.txt', skiprows=1, unpack=True )

In [19]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [20]:
# Array B
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [21]:
# Array C
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [22]:
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!

dataset = np.genfromtxt('C:/CursoDataScience/MaterialModulo4/materiais-de-apoio-numpy/dataset_valores_vazio.txt', skip_header=2, filling_values=0)

In [36]:
# Imprimindo o dataset
dataset

array([[ 0.4839,  0.4536,  0.3561],
       [ 0.1292,  0.6875,  0.    ],
       [ 0.1781,  0.3049,  0.8928],
       [ 0.    ,  0.5801,  0.2038],
       [ 0.5993,  0.4357,  0.741 ]])