# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


In [1]:
# Importando a biblioteca numpy
import numpy as np

In [2]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [3]:
type(one_dim)

numpy.ndarray

In [4]:
# Imprimindo um array.
one_dim.ndim

1

In [5]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [6]:
# Informando quantas dimensões tem o array
two_dim.ndim

2

In [9]:
# Imprimindo o array
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.68671127, 0.27107599],
       [0.76996627, 0.32753995],
       [0.83438226, 0.17415207],
       [0.82607655, 0.29762338],
       [0.27515031, 0.80854743]])

In [12]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy Arrays Vs Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [22]:
# Criando uma lista em Python.
lista = [1,2,3]

In [23]:
lista

[1, 2, 3]

In [24]:
type(lista)

list

In [17]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [25]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [26]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [20]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [28]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [29]:
# Faz o calculo usando as listas
pesos / altura ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [30]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [31]:
# Imprime o calculo de cada valor
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [32]:
# Arrays Numpy armazena elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [33]:
#colocou todos como string
a

array(['1', '3', 'Casa', 'True'], dtype='<U11')

In [34]:
a * 2 

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

# Métodos e Atributos Úteis

In [35]:
# Métodos disponíveis (digite o . pressione tab).
two_dim.

SyntaxError: invalid syntax (<ipython-input-35-538b6f2a23d9>, line 2)

In [37]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [39]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [40]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [41]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [42]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [43]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [44]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
two_dim.dtype

dtype('int32')

In [46]:
two_dim.size

6

In [49]:
# mostra a quantidade em bytes
two_dim.itemsize

4

In [50]:
# Somando todos os elementos do array.
two_dim.sum()

21

#  Transformando Arrays

In [128]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [130]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
# Transforma em uma matriz de uma linha.
# È muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [51]:
#5 linhas e 3 colunas
tree = np.random.random((5,3))

In [53]:
tree.shape

(5, 3)

In [54]:
tree

array([[0.45236314, 0.82692726, 0.35633446],
       [0.2094891 , 0.28563986, 0.2511854 ],
       [0.77642915, 0.99512541, 0.2541517 ],
       [0.4167688 , 0.86783442, 0.60944756],
       [0.75067489, 0.09811744, 0.21794413]])

In [55]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.45236314, 0.82692726, 0.35633446, 0.2094891 , 0.28563986],
       [0.2511854 , 0.77642915, 0.99512541, 0.2541517 , 0.4167688 ],
       [0.86783442, 0.60944756, 0.75067489, 0.09811744, 0.21794413]])

In [56]:
tree.reshape(-1)

array([0.45236314, 0.82692726, 0.35633446, 0.2094891 , 0.28563986,
       0.2511854 , 0.77642915, 0.99512541, 0.2541517 , 0.4167688 ,
       0.86783442, 0.60944756, 0.75067489, 0.09811744, 0.21794413])

In [57]:
t=tree.reshape(1,15)
t

array([[0.45236314, 0.82692726, 0.35633446, 0.2094891 , 0.28563986,
        0.2511854 , 0.77642915, 0.99512541, 0.2541517 , 0.4167688 ,
        0.86783442, 0.60944756, 0.75067489, 0.09811744, 0.21794413]])

In [58]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,10)

In [60]:
# Transforma em um array de uma linha.
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [62]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [63]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [64]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("C:/CursoDataScience/MaterialModulo4/Exercicios/dataset_array.txt",two_dim, delimiter=',')